services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./bookmanager:/app
    ports:
      - "5000:5000"
    env_file:
      - ./bookmanager/.env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./bookmanager/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: